name: Metrics
on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual trigger from Actions tab

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Full-year calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.fullyear.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

      - name: Recent activity charts
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.habits.charts.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_days: 14
          plugin_habits_from: activity
          config_timezone: Asia/Kolkata

      - name: Indepth analysis
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.languages.indepth.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot
          plugin_languages_indepth: yes
          plugin_languages_details: lines, bytes-size
          plugin_languages_limit: 4
          plugin_languages_analysis_timeout: 15

      - name: LeetCode
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.leetcode.svg
          token: NOT_NEEDED
          base: ""
          plugin_leetcode: yes
          plugin_leetcode_user: rizwan_molla
          plugin_leetcode_sections: solved, skills, recent
