name: Metrics
on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual trigger from Actions tab

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Full-year calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.fullyear.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

      - name: Recent activity charts
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.habits.charts.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_facts: no
          plugin_habits_charts: yes
          config_timezone: Asia/Kolkata

      - name: Full history calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.calendar.full.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_calendar: yes
          plugin_calendar_limit: 0

      - name: GitHub Skyline
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.skyline.svg
          token: NOT_NEEDED
          base: ""
          plugin_skyline: yes
          plugin_skyline_year: 2026
          plugin_skyline_frames: 6
          plugin_skyline_quality: 1

      - name: LeetCode
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.leetcode.svg
          token: NOT_NEEDED
          base: ""
          plugin_leetcode: yes
          plugin_leetcode_user: RizwanMolla
          plugin_leetcode_sections: solved, skills, recent
